---

- name: Clone the website content locally for transfer
  git:
    repo: "{{ content_repo_url }}"
    dest: "{{ tmp_hugo }}/src"

- import_tasks: setup-hugo.yaml

- name: Sync the website content with the S3 bucket
  s3_sync:
    bucket: "{{ bucket }}"
    file_root: "{{ tmp_hugo }}/src/public/"
    region: "{{ aws_region }}"
    aws_access_key: "{{ aws_access_key|default(omit) }}"
    aws_secret_key: "{{ aws_secret_key|default(omit) }}"
    validate_certs: "{{ validate_certs }}"
    permission: public-read
    file_change_strategy: "{{ force_sync|default('date_size') }}"
    delete: true
    exclude: ".git"

- name: Cleanup hugo files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ tmp_hugo }}"
  when: not keep_content|bool