---

- name: Check the existence of the public index file
  stat:
    path: "{{ tmp_hugo }}/src/public/index.html"
  register: st

- name: Include OS specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution|lower }}.yaml"
        - "{{ ansible_os_family|lower }}.yaml"
        - default.yml
      paths:
        - 'vars'

- name: Install and run hugo binary if needed
  block:
    - name: Create temporary hugo directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ tmp_hugo }}/src"
        - "{{ tmp_hugo }}/bin"
        - "{{ tmp_hugo }}/tmp"

    - name: Download hugo binary to generate static content
      get_url:
        url: "{{ hugo_url }}"
        dest: "{{ tmp_hugo }}/tmp/{{ hugo_url|basename }}"
        mode: 0755

    - name: Extract hugo binary
      unarchive:
        dest: "{{ tmp_hugo }}/bin"
        src: "{{ tmp_hugo }}/tmp/{{ hugo_url|basename }}"
  when: not st.stat.exists

- name: Run hugo binary to generate the static content
  command: "{{ tmp_hugo }}/bin/hugo"
  args:
    chdir: "{{ tmp_hugo }}/src"